[package]
name = "paragon-lexer"
version = "0.1.0"
edition = "2021"

[dependencies]
paragon-cache = { path = "../paragon-cache" }
paragon-span = { path = "../paragon-span" }
paragon-token = { path = "../paragon-token" }
thiserror = "1.0.47"
