[workspace]
members = [
    "paragon",
    "paragon-ast",
    "paragon-cache",
    "paragon-eval",
    "paragon-lexer",
    "paragon-object",
    "paragon-parser",
    "paragon-span",
    "paragon-symtable",
    "paragon-token",
]
