[package]
name = "paragon-eval"
version = "0.1.0"
edition = "2021"

[dependencies]
paragon-ast = { path = "../paragon-ast" }
paragon-object = { path = "../paragon-object" }
paragon-span = { path = "../paragon-span" }
paragon-symtable = { path = "../paragon-symtable" }
thiserror = "1.0.47"
